import { resetTestOwner } from "./reset";
import { test, expect } from "@playwright/test";
test.beforeEach(resetTestOwner);
test("private APIs reject anonymous access and unsafe writes", async ({ request }) => {
  for (const path of ["/api/projects", "/api/tasks", "/api/today", "/api/goals", "/api/analytics", "/api/focus"]) expect((await request.get(path)).status()).toBe(401);
  expect((await request.post("/api/tasks", { data: { title: "Not allowed" } })).status()).toBe(401);
  expect((await request.get("/api/cron/daily-digest")).status()).toBe(401);
  expect((await request.post("/api/auth/login", { data: { password: "boardo-test-password" }, headers: { Origin: "https://untrusted.invalid" } })).status()).toBe(403);
});
test("capture, plan, focus, complete and reflect on desktop and mobile", async ({ page }) => {
  const suffix = Date.now().toString(); const project = `Personal ${suffix}`; const task = `Write a meaningful first draft ${suffix}`;
  await page.goto("/dashboard"); await expect(page).toHaveURL(/login/);
  await page.getByLabel("Your password").fill("boardo-test-password");
  await page.getByRole("button", { name: "Open my workspace" }).click(); await expect(page).toHaveURL(/dashboard/);
  await page.getByRole("link", { name: "Goals & projects", exact: true }).click();
  await page.getByLabel("New project name").fill(project); await page.getByRole("button", { name: "Add project", exact: true }).click();
  await expect(page.getByRole("link", { name: project + " ↗" })).toBeVisible();
  await page.getByRole("link", { name: "Tasks", exact: true }).click();
  await page.getByRole("button", { name: "Add task" }).click();
  await page.getByLabel("Next action", { exact: true }).fill(task);
  await page.getByRole("combobox", { name: "Project", exact: true }).selectOption({ label: project });
  await page.getByLabel("Due date", { exact: true }).fill("2026-12-31");
  await page.getByRole("button", { name: "Add task", exact: true }).click();
  await expect(page.getByRole("heading", { name: task })).toBeVisible();
  await page.getByRole("link", { name: "Today", exact: true }).click();
  await expect(page.getByRole("heading", { name: "What matters today?" })).toBeVisible();
  const adjust = page.getByRole("button", { name: "Adjust day" }); if (await adjust.isVisible()) await adjust.click();
  await page.getByLabel("One to three outcomes").fill("Make progress on the first draft");
  await page.getByLabel("Available minutes today").fill("120");
  await page.getByLabel(task, { exact: true }).check();
  await page.getByRole("button", { name: "Save my day" }).click();
  await expect(page.getByRole("button", { name: "Adjust day" })).toBeVisible();
  await expect(page.locator(".now-card").getByRole("heading", { name: task })).toBeVisible();
  await page.screenshot({ path: "test-results/today-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator("body")).toHaveJSProperty("scrollWidth", 390);
  await page.screenshot({ path: "test-results/today-mobile.png", fullPage: true });
  await page.locator(".now-card").getByRole("button", { name: "Start focus" }).click();
  await expect(page.getByRole("button", { name: "Pause focus" })).toBeVisible();
  await page.reload(); await expect(page.getByRole("button", { name: "Pause focus" })).toBeVisible();
  await page.locator(".now-card").getByRole("button", { name: "Done", exact: false }).click();
  await expect(page.locator(".now-card").getByRole("heading", { name: task })).not.toBeVisible();
  await page.getByRole("link", { name: "Review", exact: true }).click();
  await page.getByLabel("What moved forward? What should change tomorrow?").fill("Finished the draft. Keep the next step small.");
  await page.getByRole("button", { name: "Save reflection" }).click();
  await expect(page.getByRole("status").filter({ hasText: "Reflection saved" })).toBeVisible();
  await page.reload(); await expect(page.getByLabel("What moved forward? What should change tomorrow?")).toHaveValue("Finished the draft. Keep the next step small.");
});
