"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { request } from "@/lib/client";
import { Goal, Project } from "@/lib/types";
export function ProjectsClient({ timezone }: { timezone: string }) {
  const [projects, setProjects] = useState<Project[]>([]); const [goals, setGoals] = useState<Goal[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [name, setName] = useState(""); const [title, setTitle] = useState(""); const [area, setArea] = useState("Work"); const [zone, setZone] = useState(timezone); const [showArchive, setShowArchive] = useState(false);
  const [rename, setRename] = useState<{ id: string; name: string } | null>(null);
  async function load() { const [p,g] = await Promise.all([request<Project[]>("/api/projects?archived=true"), request<Goal[]>("/api/goals")]); setProjects(p); setGoals(g); }
  useEffect(() => { const controller = new AbortController(); Promise.all([request<Project[]>("/api/projects?archived=true", "GET", undefined, controller.signal), request<Goal[]>("/api/goals", "GET", undefined, controller.signal)]).then(([p,g]) => { setProjects(p); setGoals(g); }).catch((e) => { if (!controller.signal.aborted) setError(e.message); }); return () => controller.abort(); }, []);
  async function run(action: () => Promise<unknown>) { setBusy(true); setError(""); setMessage(""); try { await action(); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Please retry."); } finally { setBusy(false); } }
  return <div><div className="page-heading"><div><p className="eyebrow">A PLACE FOR WHAT MATTERS</p><h1>Goals & projects.</h1></div></div>{error && <p role="alert" className="error">{error}<button onClick={() => void load().catch((e) => setError(e.message))}>Retry</button></p>}{message && <p role="status" className="success">{message}</p>}
    <div className="today-grid"><section className="panel"><h2>Your projects</h2><p className="muted">Organize work into useful spaces.</p><form className="inline-form" onSubmit={(e) => { e.preventDefault(); void run(async () => { await request("/api/projects", "POST", { name }); setName(""); }); }}><input aria-label="New project name" value={name} onChange={(e) => setName(e.target.value)} placeholder="A project or area of life" maxLength={150} required /><button className="button" disabled={busy}>Add project</button></form>
      <ul className="project-list">{projects.filter((p) => showArchive || !p.archived).map((p) => <li key={p.id}><div>{rename?.id === p.id ? <form className="inline-form" onSubmit={(e) => { e.preventDefault(); void run(async () => { await request("/api/projects/" + p.id, "PATCH", { name: rename.name, version: p.version }); setRename(null); }); }}><input aria-label="Project name" value={rename.name} onChange={(e) => setRename({ ...rename, name: e.target.value })} required /><button disabled={busy} className="button-secondary">Save</button><button type="button" className="button-text" onClick={() => setRename(null)}>Cancel</button></form> : <><Link href={"/projects/" + p.id} className={p.archived ? "muted" : ""} onClick={(e) => { if (p.archived) e.preventDefault(); }}>{p.name} {p.archived ? "(archived)" : "↗"}</Link><div className="actions"><button className="button-text" disabled={busy} onClick={() => setRename({ id: p.id, name: p.name })}>Rename</button><button className="button-text" disabled={busy} onClick={() => void run(() => request("/api/projects/" + p.id, "PATCH", { archived: !p.archived, version: p.version }))}>{p.archived ? "Restore" : "Archive"}</button><button className="button-text" aria-label={"Move " + p.name + " up"} disabled={busy || p.order === 0} onClick={() => void run(() => request("/api/projects/" + p.id, "PATCH", { order: Math.max(0, p.order - 1), version: p.version }))}>↑</button></div></>}</div></li>)}</ul>
      <button className="button-text" onClick={() => setShowArchive(!showArchive)}>{showArchive ? "Hide archived projects" : "Show archived projects"}</button>
    </section><section className="panel"><h2>Longer-term direction</h2><p className="muted">Connect tasks to the outcomes you care about.</p><form onSubmit={(e) => { e.preventDefault(); void run(async () => { await request("/api/goals", "POST", { title, area, importance: 3 }); setTitle(""); }); }}><label>Goal<input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="What would meaningful progress look like?" maxLength={200} required /></label><label>Life area<select value={area} onChange={(e) => setArea(e.target.value)}>{["Work", "Personal", "Health", "Learning"].map((x) => <option key={x}>{x}</option>)}</select></label><button className="button-secondary" disabled={busy}>Add goal</button></form><ul className="goal-list">{goals.map((g) => <li key={g.id}><span className="pill">{g.area}</span><h3>{g.title}</h3><label className="small">Importance<select aria-label={"Importance of " + g.title} value={g.importance} disabled={busy} onChange={(e) => void run(() => request("/api/goals/" + g.id, "PATCH", { importance: Number(e.target.value) }))}>{[1,2,3,4,5].map((n) => <option value={n} key={n}>{n}</option>)}</select></label><button disabled={busy} className="button-text" onClick={() => void run(() => request("/api/goals/" + g.id, "PATCH", { archived: true }))}>Archive goal</button></li>)}</ul></section></div>
    <section className="panel settings-panel"><h2>Your clock</h2><p className="muted">Your daily plan and reflection follow this timezone.</p><form className="inline-form" onSubmit={(e) => { e.preventDefault(); void run(async () => { await request("/api/settings", "PATCH", { timezone: zone }); setMessage("Timezone saved."); }); }}><label>Timezone<input value={zone} onChange={(e) => setZone(e.target.value)} list="timezones" /></label><datalist id="timezones">{["Asia/Calcutta","Asia/Kolkata","Asia/Dubai","Europe/London","America/New_York","America/Los_Angeles","UTC"].map((x) => <option value={x} key={x} />)}</datalist><button className="button-secondary" disabled={busy}>Save timezone</button></form></section>
  </div>;
}
