"use client";
import { useCallback, useEffect, useState } from "react";
import type { Analytics } from "@/lib/analytics";
import { request } from "@/lib/client";
import { earliestDate, shiftDate } from "@/lib/time-metrics";
const duration=(minutes:number)=>minutes<60?Math.round(minutes)+"m":Math.floor(minutes/60)+"h "+Math.round(minutes%60)+"m";
function Breakdown({title,groups}:{title:string;groups:Analytics["projects"]}) {
 const total=groups.reduce((n,g)=>n+g.seconds,0);
 return <section className="panel"><h2>{title}</h2>{groups.length?<ul className="breakdown-list">{groups.map(g=><li key={g.id}><div><strong>{g.name}</strong><span>{duration(g.seconds/60)} · {Math.round(g.seconds/Math.max(1,total)*100)}%</span></div><meter min={0} max={Math.max(1,total)} value={g.seconds} aria-label={g.name+" focus time"}/></li>)}</ul>:<p className="muted">No recorded focus in this period.</p>}</section>;
}
export function ReviewAnalytics({today,onRange}:{today:string;onRange:(start:string,end:string)=>void}) {
 const [start,setStart]=useState(today),[end,setEnd]=useState(today),[data,setData]=useState<Analytics|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0);
 const [editing,setEditing]=useState<string|null>(null),[minutes,setMinutes]=useState(""),[reason,setReason]=useState(""),[saving,setSaving]=useState(false);
 const load=useCallback(async(signal:AbortSignal)=>{setLoading(true);setError("");try{const next=await request<Analytics>("/api/analytics?"+new URLSearchParams({start,end}),"GET",undefined,signal);if(!signal.aborted)setData(next);}catch(e){if(!signal.aborted)setError(e instanceof Error?e.message:"Could not load reports.");}finally{if(!signal.aborted)setLoading(false);}},[start,end]);
 useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort();},[load,revision]);
 useEffect(()=>{const refresh=()=>setRevision(v=>v+1);const interval=setInterval(refresh,60000);window.addEventListener("boardo:changed",refresh);return()=>{clearInterval(interval);window.removeEventListener("boardo:changed",refresh);};},[]);
 function range(from:string,to:string){setStart(from);setEnd(to);onRange(from,to);}
 function preset(days:number){range(days===1096?earliestDate(today):shiftDate(today,1-days),today);}
 function exportCsv(){if(!data)return;const csv=["date,focus_minutes,planned_minutes,buffer_minutes,unused_minutes,overtime_minutes,completed_tasks",...data.days.map(d=>[d.date,(d.focusSeconds/60).toFixed(2),d.availableMinutes??"",d.bufferMinutes,d.unusedMinutes?.toFixed(2)??"",d.overtimeMinutes.toFixed(2),d.completions].join(","))].join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="boardo-"+start+"-"+end+".csv";a.click();URL.revokeObjectURL(url);}
 return <section className="analytics"><div className="panel report-controls"><div className="section-heading"><div><p className="eyebrow">YOUR TIME, IN PERSPECTIVE</p><h2>Review up to three years.</h2></div><button className="button-secondary" disabled={!data||loading||data.start!==start||data.end!==end} onClick={exportCsv}>Export daily CSV</button></div>
 <div className="actions">{[[1,"Today"],[7,"7 days"],[30,"30 days"],[90,"90 days"],[365,"1 year"],[1096,"3 years"]].map(([days,label])=><button className="button-secondary" key={label} onClick={()=>preset(Number(days))}>{label}</button>)}</div>
 <div className="form-grid"><label>From date<input type="date" min={earliestDate(today)} max={end} value={start} onChange={e=>range(e.target.value,end)}/></label><label>To date<input type="date" min={start} max={today} value={end} onChange={e=>range(start,e.target.value)}/></label></div>
 <p className="small muted">Capacity totals use explicitly confirmed plans from this release. Reflections and carried tasks alone do not imply availability. Daily, project and goal totals use your workspace timezone. Focus is recorded time, not a measure of all your activity.</p></div>
 {error&&<p className="error" role="alert">{error}<button onClick={()=>setRevision(v=>v+1)}>Retry</button></p>}
 {loading&&<p role="status">Loading your time history…</p>}
 {data&&data.start===start&&data.end===end&&!error&&<><div className="analytics-stats">{[
 [duration(data.totals.focusSeconds/60),"Recorded focus"],[duration(data.totals.unusedMinutes),end===today?"Unused / remaining capacity":"Unused planned capacity"],[duration(data.totals.bufferMinutes),"Reserved breaks / buffer"],[duration(data.totals.overtimeMinutes),"Over planned capacity"],
 [String(data.totals.completedTasks),"Tasks completed"],[String(data.totals.sessionCount),"Focus sessions"],[duration(data.totals.averageSessionMinutes),"Average session"],[data.totals.utilization===null?"—":Math.round(data.totals.utilization)+"%","Planned-time utilization"]
 ].map(([value,label])=><div className="panel" key={label}><strong className="metric-number">{value}</strong><p>{label}</p></div>)}</div>
 <p className="notice">{data.totals.plannedDays} planned days · {data.totals.missingPlanDays} days without a saved plan. Unused capacity excludes unplanned days; today&apos;s remaining time is provisional. {data.firstTrackedDate?"Recorded history begins "+data.firstTrackedDate+".":"No focus history recorded yet."} {data.totals.legacySessions>0&&"Older sessions use the task's attribution at upgrade time."}</p>
 <div className="analytics-columns"><Breakdown title="Time by project" groups={data.projects}/><Breakdown title="Time by goal" groups={data.goals}/></div>
 <section className="panel"><div className="section-heading"><h2>Consistency across your days</h2><span className="small muted">{data.totals.activeDays} days with focus</span></div><div className="heatmap" aria-label="Daily focus heatmap">{data.days.map(d=><button key={d.date} title={d.date+": "+duration(d.focusSeconds/60)+(d.availableMinutes===null?" · No plan":"")} aria-label={d.date+": "+duration(d.focusSeconds/60)+" focus. Open day."} style={{background:d.focusSeconds?["#dce9c6","#a4c18a","#5b865f","#245941"][Math.min(3,Math.floor(d.focusSeconds/3600))]:"#eeeee8"}} onClick={()=>range(d.date,d.date)}/>)}</div><p className="small muted">Darker squares mean more recorded focus. Select a day to explore it; blank days mean no recorded focus.</p></section>
 <section className="panel"><h2>Daily time ledger</h2><div className="table-scroll" tabIndex={0} aria-label="Daily time ledger"><table><thead><tr><th>Date</th><th>Focus</th><th>Plan</th><th>Buffer</th><th>Unused</th><th>Over</th><th>Done</th></tr></thead><tbody>{[...data.days].reverse().map(d=><tr key={d.date}><th><button className="button-text" onClick={()=>range(d.date,d.date)}>{d.date}</button></th><td>{duration(d.focusSeconds/60)}</td><td>{d.availableMinutes===null?"No plan":duration(d.availableMinutes)}</td><td>{duration(d.bufferMinutes)}</td><td>{d.unusedMinutes===null?"—":duration(d.unusedMinutes)}</td><td>{duration(d.overtimeMinutes)}</td><td>{d.completions}</td></tr>)}</tbody></table></div></section>
 <section className="panel"><h2>Focus session history</h2><p className="small muted">Latest {data.sessions.length} of {data.sessionTotal} sessions in this range. Narrow the dates for older entries. Corrections remove accidental time and retain an audit record.</p><div className="session-history">{data.sessions.map(s=><article key={s.id} className="session-row"><div><strong>{s.taskTitle||"Deleted task"}</strong><p className="small muted">{s.projectName} {s.goalTitle?" / "+s.goalTitle:""} · {new Date(s.startedAt).toLocaleString([],{timeZone:data.timezone})}</p><p>{duration(s.seconds/60)} in this range · {s.running?"Running":s.capped?"Stopped at session limit":s.stopReason||"Saved"}{s.correctionNote?" · Corrected: "+s.correctionNote:""}</p></div>
 {!s.running&&<button className="button-text" onClick={()=>{setEditing(s.id);setMinutes(String(Math.floor((Date.parse(s.effectiveEnd)-new Date(s.startedAt).getTime())/60000)));setReason("");}}>Correct time</button>}
 {editing===s.id&&<form className="correction-form" onSubmit={e=>{e.preventDefault();setSaving(true);void request("/api/focus","POST",{id:s.id,version:s.version,action:"correct",minutes:Number(minutes),reason}).then(()=>{setEditing(null);setRevision(v=>v+1);window.dispatchEvent(new Event("boardo:changed"));}).catch(e=>setError(e.message)).finally(()=>setSaving(false));}}><label>Corrected total minutes<input type="number" min={0} max={180} value={minutes} onChange={e=>setMinutes(e.target.value)} required/></label><label>Reason for correction<input value={reason} onChange={e=>setReason(e.target.value)} minLength={3} maxLength={500} required/></label><button disabled={saving} className="button">Save correction</button><button type="button" className="button-text" onClick={()=>setEditing(null)}>Cancel</button></form>}</article>)}</div>{!data.sessions.length&&<p className="muted">Start a focus session to build your history.</p>}</section>
 <div className="analytics-columns"><section className="panel"><h2>The shape of your day</h2><p className="small muted">{data.activity.length} of {data.activityTotal} events shown · {data.timezone}. Narrow the date range for earlier events.</p><ol className="activity-list activity-scroll" tabIndex={0} aria-label="Scrollable activity history">{data.activity.map(e=><li key={e.id}><span className="small muted">{new Date(e.createdAt).toLocaleString([],{timeZone:data.timezone,dateStyle:"short",timeStyle:"short"})}</span><div><strong>{e.action.replaceAll("_"," ")}</strong><p>{e.taskTitle||"Workspace update"}</p>{e.detail&&<p className="small muted">{e.detail}</p>}</div></li>)}</ol></section>
 <section className="panel"><h2>Past reflections</h2><div className="activity-scroll">{data.reflections.length?data.reflections.map(r=><article key={r.date}><h3>{r.date}</h3><p className="reflection-text">{r.review}</p></article>):<p className="muted">Saved reflections for this period will appear here.</p>}</div></section></div>
 </>}
 </section>;
}
